ktor {
    deployment {
        port = 8080
    }
}

database {
    url         = "jdbc:postgresql://localhost:5433/reserveo"
    url         = ${?DB_URL}
    driver      = "org.postgresql.Driver"
    user        = "reserveo"
    user        = ${?DB_USER}
    password    = "reserveo"
    password    = ${?DB_PASSWORD}
    maxPoolSize = 10
}
